version: "3.7"
services:
  db_product:
    image: mongo
    container_name: db_product
    ports:
      - "27018:27017"
    environment:
      - "MONGO_INITDB_DATABASE=bootcamp_product_db"
  ms-customer:
    image: service-product
    container_name: service-product
    depends_on:
      - db_product
    ports:
      - "8004:8000"